"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const NumbersCollection_1 = require("./NumbersCollection");
const CharactersCollection_1 = require("./CharactersCollection");
const LinkedList_1 = require("./LinkedList");
const numbersCollection = new NumbersCollection_1.NumbersCollection([14, 2, 550, 69, 420]);
numbersCollection.sort();
console.log(numbersCollection.data);
const charactersCollection = new CharactersCollection_1.CharactersCollection('Paco est à la pizzeria');
charactersCollection.sort();
console.log(charactersCollection.data);
const linkedListCollection = new LinkedList_1.LinkedList();
linkedListCollection.add(500);
linkedListCollection.add(-10);
linkedListCollection.add(-5);
linkedListCollection.add(4);
linkedListCollection.sort();
linkedListCollection.print();
